name: Daily XP Leaderboard

on:
  schedule:
    # 7am UK time in summer (BST) is 6am UTC
    - cron: '0 6 * * *'
    # 7am UK time in winter (GMT) is 7am UTC
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run XP Leaderboard Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scrape_xp_tab9.py

      - name: Commit & Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add xp_log.json monthly_xp.json
          git diff --cached --quiet || git commit -m "Automated daily XP update"
          git pull --rebase --autostash
          git push
